a=input('digite algo : ')
print('o tipo primitivo deste valor é',type(a))
print('so tem espaços ?:',a.isspace())
print('è um numero ?',a.isnumeric())
print('é alfabético ?' ,a.isalpha())
print('é alfanumérico?',a.isalnum())
print('esta em maiusculo ?',a.isupper())
print(' esta em minusculo ?',a.islower())
print('esta captalizada ?' ,a.istitle())